;;; -*- Mode : lisp -*-
;;; This file was automatically generated by WRITE-JAVA-CLASS-DEFINITIONS-TO-FILE


;;; Definitions for Java class   com.itextpdf.kernel.pdf.PdfReader 


(eval-when (compile load eval)
  (let ((package-name "com.itextpdf.kernel.pdf"))
    (unless (find-package package-name) (make-package package-name)))
  (lw-ji:intern-and-export-list '("PDFREADER.GETPERMISSIONS"
                                  "PDFREADER.HASXREFSTM"
                                  "PDFREADER.SETCLOSESTREAM"
                                  "PDFREADER.HASREBUILTXREF"
                                  "PDFREADER.READSTREAMBYTESRAW"
                                  "PDFREADER.COMPUTEUSERPASSWORD"
                                  "PDFREADER.GETMODIFIEDFILEID"
                                  "PDFREADER.TOSTRING"
                                  "PDFREADER.CLOSE"
                                  "PDFREADER.GETCLASS"
                                  "PDFREADER.EQUALS"
                                  "PDFREADER.SETUNETHICALREADING"
                                  "PDFREADER.GETLASTXREF"
                                  "PDFREADER.NOTIFY"
                                  "PDFREADER.GETCRYPTOMODE"
                                  "PDFREADER.ISENCRYPTED"
                                  "PDFREADER.HASHYBRIDXREF"
                                  "PDFREADER.READSTREAM"
                                  "PDFREADER.GETFILELENGTH"
                                  "PDFREADER.ISOPENEDWITHFULLPERMISSION"
                                  "PDFREADER.HASFIXEDXREF"
                                  "PDFREADER.ISCLOSESTREAM"
                                  "PDFREADER.NOTIFYALL"
                                  "PDFREADER.HASHCODE"
                                  "PDFREADER.GETSAFEFILE"
                                  "PDFREADER.GETORIGINALFILEID"
                                  "PDFREADER.WAIT"
                                  "PDFREADER.DECODEBYTES"
                                  "PDFREADER.GETPDFACONFORMANCELEVEL"
                                  "PDFREADER.READSTREAMBYTES"
                                  "PDFREADER.NEW"
                                  "PDFREADER.")
                                "com.itextpdf.kernel.pdf"))

(in-package "com.itextpdf.kernel.pdf")
(defconstant pdfreader. "com.itextpdf.kernel.pdf.PdfReader")
(lw-ji:record-java-class-lisp-symbol "com.itextpdf.kernel.pdf.PdfReader"
                                     'pdfreader.)
(lw-ji:define-java-constructor pdfreader.new
                               "com.itextpdf.kernel.pdf.PdfReader"
                               :signatures
                               ("com.itextpdf.kernel.pdf.PdfReader(java.io.File)"
                                "com.itextpdf.kernel.pdf.PdfReader(java.io.InputStream,com.itextpdf.kernel.pdf.ReaderProperties)"
                                "com.itextpdf.kernel.pdf.PdfReader(com.itextpdf.io.source.IRandomAccessSource,com.itextpdf.kernel.pdf.ReaderProperties)"
                                "com.itextpdf.kernel.pdf.PdfReader(java.io.InputStream)"
                                "com.itextpdf.kernel.pdf.PdfReader(java.lang.String,com.itextpdf.kernel.pdf.ReaderProperties)"
                                "com.itextpdf.kernel.pdf.PdfReader(java.lang.String)")
                               :class-symbol
                               nil)
(lw-ji:define-java-caller pdfreader.getpermissions
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "getPermissions"
                          :signatures
                          ("public long getPermissions()"))
(lw-ji:define-java-caller pdfreader.hasxrefstm
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "hasXrefStm"
                          :signatures
                          ("public boolean hasXrefStm()"))
(lw-ji:define-java-caller pdfreader.setclosestream
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "setCloseStream"
                          :signatures
                          ("public void setCloseStream(boolean)"))
(lw-ji:define-java-caller pdfreader.hasrebuiltxref
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "hasRebuiltXref"
                          :signatures
                          ("public boolean hasRebuiltXref()"))
(lw-ji:define-java-caller pdfreader.readstreambytesraw
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "readStreamBytesRaw"
                          :signatures
                          ("public byte[] readStreamBytesRaw(com.itextpdf.kernel.pdf.PdfStream)"))
(lw-ji:define-java-caller pdfreader.computeuserpassword
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "computeUserPassword"
                          :signatures
                          ("public byte[] computeUserPassword()"))
(lw-ji:define-java-caller pdfreader.getmodifiedfileid
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "getModifiedFileId"
                          :signatures
                          ("public byte[] getModifiedFileId()"))
(lw-ji:define-java-caller pdfreader.tostring
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "toString"
                          :signatures
                          ("public java.lang.String toString()"))
(lw-ji:define-java-caller pdfreader.close
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "close"
                          :signatures
                          ("public void close()"))
(lw-ji:define-java-caller pdfreader.getclass
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "getClass"
                          :signatures
                          ("public final java.lang.Class getClass()"))
(lw-ji:define-java-caller pdfreader.equals
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "equals"
                          :signatures
                          ("public boolean equals(java.lang.Object)"))
(lw-ji:define-java-caller pdfreader.setunethicalreading
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "setUnethicalReading"
                          :signatures
                          ("public com.itextpdf.kernel.pdf.PdfReader setUnethicalReading(boolean)"))
(lw-ji:define-java-caller pdfreader.getlastxref
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "getLastXref"
                          :signatures
                          ("public long getLastXref()"))
(lw-ji:define-java-caller pdfreader.notify
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "notify"
                          :signatures
                          ("public final void notify()"))
(lw-ji:define-java-caller pdfreader.getcryptomode
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "getCryptoMode"
                          :signatures
                          ("public int getCryptoMode()"))
(lw-ji:define-java-caller pdfreader.isencrypted
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "isEncrypted"
                          :signatures
                          ("public boolean isEncrypted()"))
(lw-ji:define-java-caller pdfreader.hashybridxref
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "hasHybridXref"
                          :signatures
                          ("public boolean hasHybridXref()"))
(lw-ji:define-java-caller pdfreader.readstream
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "readStream"
                          :signatures
                          ("public java.io.InputStream readStream(com.itextpdf.kernel.pdf.PdfStream, boolean)"))
(lw-ji:define-java-caller pdfreader.getfilelength
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "getFileLength"
                          :signatures
                          ("public long getFileLength()"))
(lw-ji:define-java-caller pdfreader.isopenedwithfullpermission
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "isOpenedWithFullPermission"
                          :signatures
                          ("public boolean isOpenedWithFullPermission()"))
(lw-ji:define-java-caller pdfreader.hasfixedxref
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "hasFixedXref"
                          :signatures
                          ("public boolean hasFixedXref()"))
(lw-ji:define-java-caller pdfreader.isclosestream
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "isCloseStream"
                          :signatures
                          ("public boolean isCloseStream()"))
(defsetf pdfreader.isclosestream pdfreader.setclosestream)
(lw-ji:define-java-caller pdfreader.notifyall
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "notifyAll"
                          :signatures
                          ("public final void notifyAll()"))
(lw-ji:define-java-caller pdfreader.hashcode
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "hashCode"
                          :signatures
                          ("public int hashCode()"))
(lw-ji:define-java-caller pdfreader.getsafefile
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "getSafeFile"
                          :signatures
                          ("public com.itextpdf.io.source.RandomAccessFileOrArray getSafeFile()"))
(lw-ji:define-java-caller pdfreader.getoriginalfileid
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "getOriginalFileId"
                          :signatures
                          ("public byte[] getOriginalFileId()"))
(lw-ji:define-java-caller pdfreader.wait
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "wait"
                          :signatures
                          ("public final void wait(long)"
                           "public final void wait(long, int)"
                           "public final void wait()"))
(lw-ji:define-java-caller pdfreader.decodebytes
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "decodeBytes"
                          :signatures
                          ("public static byte[] decodeBytes(byte[], com.itextpdf.kernel.pdf.PdfDictionary, java.util.Map)"
                           "public static byte[] decodeBytes(byte[], com.itextpdf.kernel.pdf.PdfDictionary)"))
(lw-ji:define-java-caller pdfreader.getpdfaconformancelevel
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "getPdfAConformanceLevel"
                          :signatures
                          ("public com.itextpdf.kernel.pdf.PdfAConformanceLevel getPdfAConformanceLevel()"))
(lw-ji:define-java-caller pdfreader.readstreambytes
                          "com/itextpdf/kernel/pdf/PdfReader"
                          "readStreamBytes"
                          :signatures
                          ("public byte[] readStreamBytes(com.itextpdf.kernel.pdf.PdfStream, boolean)"))

;;; End of class   com.itextpdf.kernel.pdf.PdfReader 

