;;; -*- Mode : lisp -*-
;;; This file was automatically generated by WRITE-JAVA-CLASS-DEFINITIONS-TO-FILE


;;; Definitions for Java class   org.apache.pdfbox.pdmodel.PDDocument 


(eval-when (compile load eval)
  (let ((package-name "org.apache.pdfbox.pdmodel"))
    (unless (find-package package-name) (make-package package-name)))
  (lw-ji:intern-and-export-list '("PDDOCUMENT.LOAD"
                                  "PDDOCUMENT.GETENCRYPTION"
                                  "PDDOCUMENT.GETVERSION"
                                  "PDDOCUMENT.CLOSE"
                                  "PDDOCUMENT.SAVEINCREMENTALFOREXTERNALSIGNING"
                                  "PDDOCUMENT.GETDOCUMENTID"
                                  "PDDOCUMENT.GETRESOURCECACHE"
                                  "PDDOCUMENT.SETENCRYPTIONDICTIONARY"
                                  "PDDOCUMENT.SAVE"
                                  "PDDOCUMENT.ADDSIGNATURE"
                                  "PDDOCUMENT.ISALLSECURITYTOBEREMOVED"
                                  "PDDOCUMENT.NOTIFYALL"
                                  "PDDOCUMENT.ADDPAGE"
                                  "PDDOCUMENT.SETVERSION"
                                  "PDDOCUMENT.REGISTERTRUETYPEFONTFORCLOSING"
                                  "PDDOCUMENT.HASHCODE"
                                  "PDDOCUMENT.GETLASTSIGNATUREDICTIONARY"
                                  "PDDOCUMENT.GETCURRENTACCESSPERMISSION"
                                  "PDDOCUMENT.ISENCRYPTED"
                                  "PDDOCUMENT.GETDOCUMENT"
                                  "PDDOCUMENT.IMPORTPAGE"
                                  "PDDOCUMENT.NOTIFY"
                                  "PDDOCUMENT.WAIT"
                                  "PDDOCUMENT.ADDSIGNATUREFIELD"
                                  "PDDOCUMENT.GETSIGNATUREDICTIONARIES"
                                  "PDDOCUMENT.SETDOCUMENTID"
                                  "PDDOCUMENT.GETDOCUMENTCATALOG"
                                  "PDDOCUMENT.GETCLASS"
                                  "PDDOCUMENT.SETRESOURCECACHE"
                                  "PDDOCUMENT.EQUALS"
                                  "PDDOCUMENT.GETSIGNATUREFIELDS"
                                  "PDDOCUMENT.GETPAGES"
                                  "PDDOCUMENT.GETNUMBEROFPAGES"
                                  "PDDOCUMENT.GETPAGE"
                                  "PDDOCUMENT.SETDOCUMENTINFORMATION"
                                  "PDDOCUMENT.SETALLSECURITYTOBEREMOVED"
                                  "PDDOCUMENT.SAVEINCREMENTAL"
                                  "PDDOCUMENT.REMOVEPAGE"
                                  "PDDOCUMENT.TOSTRING"
                                  "PDDOCUMENT.PROTECT"
                                  "PDDOCUMENT.GETDOCUMENTINFORMATION"
                                  "PDDOCUMENT.NEW"
                                  "PDDOCUMENT.")
                                "org.apache.pdfbox.pdmodel"))

(in-package "org.apache.pdfbox.pdmodel")
(defconstant pddocument. "org.apache.pdfbox.pdmodel.PDDocument")
(lw-ji:record-java-class-lisp-symbol "org.apache.pdfbox.pdmodel.PDDocument"
                                     'pddocument.)
(lw-ji:define-java-constructor pddocument.new
                               "org.apache.pdfbox.pdmodel.PDDocument"
                               :signatures
                               ("org.apache.pdfbox.pdmodel.PDDocument()"
                                "org.apache.pdfbox.pdmodel.PDDocument(org.apache.pdfbox.io.MemoryUsageSetting)"
                                "org.apache.pdfbox.pdmodel.PDDocument(org.apache.pdfbox.cos.COSDocument)"
                                "org.apache.pdfbox.pdmodel.PDDocument(org.apache.pdfbox.cos.COSDocument,org.apache.pdfbox.io.RandomAccessRead)"
                                "org.apache.pdfbox.pdmodel.PDDocument(org.apache.pdfbox.cos.COSDocument,org.apache.pdfbox.io.RandomAccessRead,org.apache.pdfbox.pdmodel.encryption.AccessPermission)")
                               :class-symbol
                               nil)
(lw-ji:define-java-caller pddocument.load
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "load"
                          :signatures
                          ("public static org.apache.pdfbox.pdmodel.PDDocument load(java.io.File, java.lang.String, java.io.InputStream, java.lang.String)"
                           "public static org.apache.pdfbox.pdmodel.PDDocument load(java.io.InputStream, java.lang.String, java.io.InputStream, java.lang.String, org.apache.pdfbox.io.MemoryUsageSetting)"
                           "public static org.apache.pdfbox.pdmodel.PDDocument load(java.io.InputStream, java.lang.String, org.apache.pdfbox.io.MemoryUsageSetting)"
                           "public static org.apache.pdfbox.pdmodel.PDDocument load(java.io.InputStream, java.lang.String, java.io.InputStream, java.lang.String)"
                           "public static org.apache.pdfbox.pdmodel.PDDocument load(java.io.InputStream, java.lang.String)"
                           "public static org.apache.pdfbox.pdmodel.PDDocument load(byte[], java.lang.String, java.io.InputStream, java.lang.String, org.apache.pdfbox.io.MemoryUsageSetting)"
                           "public static org.apache.pdfbox.pdmodel.PDDocument load(byte[], java.lang.String, java.io.InputStream, java.lang.String)"
                           "public static org.apache.pdfbox.pdmodel.PDDocument load(byte[], java.lang.String)"
                           "public static org.apache.pdfbox.pdmodel.PDDocument load(byte[])"
                           "public static org.apache.pdfbox.pdmodel.PDDocument load(java.io.File, org.apache.pdfbox.io.MemoryUsageSetting)"
                           "public static org.apache.pdfbox.pdmodel.PDDocument load(java.io.File, java.lang.String, org.apache.pdfbox.io.MemoryUsageSetting)"
                           "public static org.apache.pdfbox.pdmodel.PDDocument load(java.io.File, java.lang.String)"
                           "public static org.apache.pdfbox.pdmodel.PDDocument load(java.io.File)"
                           "public static org.apache.pdfbox.pdmodel.PDDocument load(java.io.InputStream, org.apache.pdfbox.io.MemoryUsageSetting)"
                           "public static org.apache.pdfbox.pdmodel.PDDocument load(java.io.InputStream)"
                           "public static org.apache.pdfbox.pdmodel.PDDocument load(java.io.File, java.lang.String, java.io.InputStream, java.lang.String, org.apache.pdfbox.io.MemoryUsageSetting)"))
(lw-ji:define-java-caller pddocument.getencryption
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "getEncryption"
                          :signatures
                          ("public org.apache.pdfbox.pdmodel.encryption.PDEncryption getEncryption()"))
(lw-ji:define-java-caller pddocument.getversion
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "getVersion"
                          :signatures
                          ("public float getVersion()"))
(lw-ji:define-java-caller pddocument.close
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "close"
                          :signatures
                          ("public void close()"))
(lw-ji:define-java-caller pddocument.saveincrementalforexternalsigning
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "saveIncrementalForExternalSigning"
                          :signatures
                          ("public org.apache.pdfbox.pdmodel.interactive.digitalsignature.ExternalSigningSupport saveIncrementalForExternalSigning(java.io.OutputStream)"))
(lw-ji:define-java-caller pddocument.getdocumentid
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "getDocumentId"
                          :signatures
                          ("public java.lang.Long getDocumentId()"))
(lw-ji:define-java-caller pddocument.getresourcecache
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "getResourceCache"
                          :signatures
                          ("public org.apache.pdfbox.pdmodel.ResourceCache getResourceCache()"))
(lw-ji:define-java-caller pddocument.setencryptiondictionary
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "setEncryptionDictionary"
                          :signatures
                          ("public void setEncryptionDictionary(org.apache.pdfbox.pdmodel.encryption.PDEncryption)"))
(lw-ji:define-java-caller pddocument.save
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "save"
                          :signatures
                          ("public void save(java.lang.String)"
                           "public void save(java.io.OutputStream)"
                           "public void save(java.io.File)"))
(lw-ji:define-java-caller pddocument.addsignature
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "addSignature"
                          :signatures
                          ("public void addSignature(org.apache.pdfbox.pdmodel.interactive.digitalsignature.PDSignature, org.apache.pdfbox.pdmodel.interactive.digitalsignature.SignatureOptions)"
                           "public void addSignature(org.apache.pdfbox.pdmodel.interactive.digitalsignature.PDSignature, org.apache.pdfbox.pdmodel.interactive.digitalsignature.SignatureInterface)"
                           "public void addSignature(org.apache.pdfbox.pdmodel.interactive.digitalsignature.PDSignature)"
                           "public void addSignature(org.apache.pdfbox.pdmodel.interactive.digitalsignature.PDSignature, org.apache.pdfbox.pdmodel.interactive.digitalsignature.SignatureInterface, org.apache.pdfbox.pdmodel.interactive.digitalsignature.SignatureOptions)"))
(lw-ji:define-java-caller pddocument.isallsecuritytoberemoved
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "isAllSecurityToBeRemoved"
                          :signatures
                          ("public boolean isAllSecurityToBeRemoved()"))
(defsetf pddocument.isallsecuritytoberemoved
         pddocument.setallsecuritytoberemoved)
(lw-ji:define-java-caller pddocument.notifyall
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "notifyAll"
                          :signatures
                          ("public final void notifyAll()"))
(lw-ji:define-java-caller pddocument.addpage
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "addPage"
                          :signatures
                          ("public void addPage(org.apache.pdfbox.pdmodel.PDPage)"))
(lw-ji:define-java-caller pddocument.setversion
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "setVersion"
                          :signatures
                          ("public void setVersion(float)"))
(lw-ji:define-java-caller pddocument.registertruetypefontforclosing
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "registerTrueTypeFontForClosing"
                          :signatures
                          ("public void registerTrueTypeFontForClosing(org.apache.fontbox.ttf.TrueTypeFont)"))
(lw-ji:define-java-caller pddocument.hashcode
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "hashCode"
                          :signatures
                          ("public int hashCode()"))
(lw-ji:define-java-caller pddocument.getlastsignaturedictionary
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "getLastSignatureDictionary"
                          :signatures
                          ("public org.apache.pdfbox.pdmodel.interactive.digitalsignature.PDSignature getLastSignatureDictionary()"))
(lw-ji:define-java-caller pddocument.getcurrentaccesspermission
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "getCurrentAccessPermission"
                          :signatures
                          ("public org.apache.pdfbox.pdmodel.encryption.AccessPermission getCurrentAccessPermission()"))
(lw-ji:define-java-caller pddocument.isencrypted
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "isEncrypted"
                          :signatures
                          ("public boolean isEncrypted()"))
(lw-ji:define-java-caller pddocument.getdocument
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "getDocument"
                          :signatures
                          ("public org.apache.pdfbox.cos.COSDocument getDocument()"))
(lw-ji:define-java-caller pddocument.importpage
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "importPage"
                          :signatures
                          ("public org.apache.pdfbox.pdmodel.PDPage importPage(org.apache.pdfbox.pdmodel.PDPage)"))
(lw-ji:define-java-caller pddocument.notify
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "notify"
                          :signatures
                          ("public final void notify()"))
(lw-ji:define-java-caller pddocument.wait
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "wait"
                          :signatures
                          ("public final void wait(long)"
                           "public final void wait(long, int)"
                           "public final void wait()"))
(lw-ji:define-java-caller pddocument.addsignaturefield
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "addSignatureField"
                          :signatures
                          ("public void addSignatureField(java.util.List, org.apache.pdfbox.pdmodel.interactive.digitalsignature.SignatureInterface, org.apache.pdfbox.pdmodel.interactive.digitalsignature.SignatureOptions)"))
(lw-ji:define-java-caller pddocument.getsignaturedictionaries
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "getSignatureDictionaries"
                          :signatures
                          ("public java.util.List getSignatureDictionaries()"))
(lw-ji:define-java-caller pddocument.setdocumentid
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "setDocumentId"
                          :signatures
                          ("public void setDocumentId(java.lang.Long)"))
(lw-ji:define-java-caller pddocument.getdocumentcatalog
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "getDocumentCatalog"
                          :signatures
                          ("public org.apache.pdfbox.pdmodel.PDDocumentCatalog getDocumentCatalog()"))
(lw-ji:define-java-caller pddocument.getclass
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "getClass"
                          :signatures
                          ("public final java.lang.Class getClass()"))
(lw-ji:define-java-caller pddocument.setresourcecache
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "setResourceCache"
                          :signatures
                          ("public void setResourceCache(org.apache.pdfbox.pdmodel.ResourceCache)"))
(lw-ji:define-java-caller pddocument.equals
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "equals"
                          :signatures
                          ("public boolean equals(java.lang.Object)"))
(lw-ji:define-java-caller pddocument.getsignaturefields
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "getSignatureFields"
                          :signatures
                          ("public java.util.List getSignatureFields()"))
(lw-ji:define-java-caller pddocument.getpages
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "getPages"
                          :signatures
                          ("public org.apache.pdfbox.pdmodel.PDPageTree getPages()"))
(lw-ji:define-java-caller pddocument.getnumberofpages
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "getNumberOfPages"
                          :signatures
                          ("public int getNumberOfPages()"))
(lw-ji:define-java-caller pddocument.getpage
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "getPage"
                          :signatures
                          ("public org.apache.pdfbox.pdmodel.PDPage getPage(int)"))
(lw-ji:define-java-caller pddocument.setdocumentinformation
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "setDocumentInformation"
                          :signatures
                          ("public void setDocumentInformation(org.apache.pdfbox.pdmodel.PDDocumentInformation)"))
(lw-ji:define-java-caller pddocument.setallsecuritytoberemoved
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "setAllSecurityToBeRemoved"
                          :signatures
                          ("public void setAllSecurityToBeRemoved(boolean)"))
(lw-ji:define-java-caller pddocument.saveincremental
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "saveIncremental"
                          :signatures
                          ("public void saveIncremental(java.io.OutputStream)"))
(lw-ji:define-java-caller pddocument.removepage
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "removePage"
                          :signatures
                          ("public void removePage(int)"
                           "public void removePage(org.apache.pdfbox.pdmodel.PDPage)"))
(lw-ji:define-java-caller pddocument.tostring
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "toString"
                          :signatures
                          ("public java.lang.String toString()"))
(lw-ji:define-java-caller pddocument.protect
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "protect"
                          :signatures
                          ("public void protect(org.apache.pdfbox.pdmodel.encryption.ProtectionPolicy)"))
(lw-ji:define-java-caller pddocument.getdocumentinformation
                          "org/apache/pdfbox/pdmodel/PDDocument"
                          "getDocumentInformation"
                          :signatures
                          ("public org.apache.pdfbox.pdmodel.PDDocumentInformation getDocumentInformation()"))

;;; End of class   org.apache.pdfbox.pdmodel.PDDocument 

